config/routes.rb
        to: 'users/settings/teams#description_html',
        as: 'team_description'
    put 'users/settings/teams/:id',
        to: 'users/settings/teams#update',
        as: 'update_team'
    delete 'users/settings/teams/:id',
           to: 'users/settings/teams#destroy',
           as: 'destroy_team'

    put 'users/settings/user_teams/:id',
        to: 'users/settings/user_teams#update',
        as: 'update_user_team'
    get 'users/settings/user_teams/:id/leave_html',
        to: 'users/settings/user_teams#leave_html',
        as: 'leave_user_team_html'
    get 'users/settings/user_teams/:id/destroy_html',
        to: 'users/settings/user_teams#destroy_html',
        as: 'destroy_user_team_html'
    delete 'users/settings/user_teams/:id',
           to: 'users/settings/user_teams#destroy',
           as: 'destroy_user_team'

    # Invite users
    devise_scope :user do
      post '/invite',
           to: 'users/invitations#invite_users',
           as: 'invite_users'
    end

    # Notifications
    get 'users/:id/recent_notifications',
        to: 'user_notifications#recent_notifications',
        as: 'recent_notifications',
        defaults: { format: 'json' }

    get 'users/:id/unseen_notification',
        to: 'user_notifications#unseen_notification',
        as: 'unseen_notification',
        defaults: { format: 'json' }

    get 'users/notifications',
        to: 'user_notifications#index',
        as: 'notifications'

    # Get Zip Export
    get 'zip_exports/download/:id',
        to: 'zip_exports#download',
        as: 'zip_exports_download'

    # Get Team Zip Export
    get 'zip_exports/download_export_all_zip/:id',
        to: 'zip_exports#download_export_all_zip',
        as: 'zip_exports_download_export_all'

    get 'zip_exports/file_expired',
        to: 'zip_exports#file_expired',
        as: 'file_expired'

    resources :teams do
      resources :repositories, only: %i(index create destroy update) do
        collection do
          get 'create_modal', to: 'repositories#create_modal',
              defaults: { format: 'json' }
        end
        get 'destroy_modal', to: 'repositories#destroy_modal',
            defaults: { format: 'json' }
        get 'rename_modal', to: 'repositories#rename_modal',
            defaults: { format: 'json' }
        get 'copy_modal', to: 'repositories#copy_modal',
            defaults: { format: 'json' }
        post 'copy', to: 'repositories#copy',
             defaults: { format: 'json' }
        get :share_modal

        resources :team_repositories, only: %i(destroy) do
          collection do
            post 'update'
          end
        end
      end
      # resources :samples, only: [:new, :create]
      # resources :sample_types, except: [:show, :new] do
      #   get 'sample_type_element', to: 'sample_types#sample_type_element'
      #   get 'destroy_confirmation', to: 'sample_types#destroy_confirmation'
      # end
      # resources :sample_groups, except: [:show, :new] do
      #   get 'sample_group_element', to: 'sample_groups#sample_group_element'
      #   get 'destroy_confirmation', to: 'sample_groups#destroy_confirmation'
      # end
      # resources :custom_fields, only: [:create, :edit, :update, :destroy] do
      #   get 'destroy_html'
      # end
      member do
        post 'parse_sheet', defaults: { format: 'json' }
        post 'export_repository', to: 'repositories#export_repository'
        post 'export_projects'
        get 'export_projects_modal'
        # Used for atwho (smart annotations)
        get 'atwho_users', to: 'at_who#users'
        get 'atwho_repositories', to: 'at_who#repositories'
        get 'atwho_rep_items', to: 'at_who#rep_items'
        get 'atwho_projects', to: 'at_who#projects'
        get 'atwho_experiments', to: 'at_who#experiments'
        get 'atwho_my_modules', to: 'at_who#my_modules'
        get 'atwho_menu_items', to: 'at_who#menu_items'
      end

      # External protocols routes
      get 'list_external_protocol', to: 'external_protocols#index'
      get 'show_external_protocol', to: 'external_protocols#show'
      get 'build_external_protocol', to: 'external_protocols#new'
      post 'import_external_protocol', to: 'external_protocols#create'

      match '*path',
            to: 'teams#routing_error',
            via: [:get, :post, :put, :patch]
    end

    post 'projects/index_dt', to: 'projects#index_dt', as: 'projects_index_dt'
    get 'projects/sidebar', to: 'projects#sidebar', as: 'projects_sidebar'
    get 'projects/dt_state_load', to: 'projects#dt_state_load',
                                  as: 'projects_dt_state_load'

    resources :reports, only: :index
    get 'reports/datatable', to: 'reports#datatable'
    post 'reports/visible_projects', to: 'reports#visible_projects',
                                     defaults: { format: 'json' }
    post 'reports/available_repositories', to: 'reports#available_repositories',
                                           defaults: { format: 'json' }
    post 'reports/save_pdf_to_inventory_item',
         to: 'reports#save_pdf_to_inventory_item',
         defaults: { format: 'json' }
    post 'available_asset_type_columns',
          to: 'repository_columns#available_asset_type_columns',
          defaults: { format: 'json' }
    post 'reports/destroy', to: 'reports#destroy'

    resources :projects, except: [:new, :destroy] do
      resources :user_projects, path: '/users',
                only: [:create, :index, :update, :destroy]
      resources :project_comments,
                path: '/comments',
                only: [:create, :index, :edit, :update, :destroy]
      # Activities popup (JSON) for individual project in projects index,
      # as well as all activities page for single project (HTML)
      resources :project_activities, path: '/activities', only: [:index]
      resources :tags, only: [:create, :update, :destroy]
      resources :reports,
                path: '/reports',
                only: %i(edit update create) do
        collection do
          # The posts following here should in theory be gets,
          # but are posts because of parameters payload
          post 'generate', to: 'reports#generate', format: %w(docx pdf)
          get 'new/', to: 'reports#new'
          get 'new/project_contents_modal',
              to: 'reports#project_contents_modal',
              as: :project_contents_modal
          post 'new/project_contents',
               to: 'reports#project_contents',
               as: :project_contents
          get 'new/experiment_contents_modal',
              to: 'reports#experiment_contents_modal',
              as: :experiment_contents_modal
          post 'new/experiment_contents',
               to: 'reports#experiment_contents',
               as: :experiment_contents
          get 'new/module_contents_modal',
              to: 'reports#module_contents_modal',
              as: :module_contents_modal
          post 'new/module_contents',
               to: 'reports#module_contents',
               as: :module_contents
          get 'new/step_contents_modal',
              to: 'reports#step_contents_modal',
              as: :step_contents_modal
          post 'new/step_contents',
               to: 'reports#step_contents',
               as: :step_contents
          get 'new/result_contents_modal',
              to: 'reports#result_contents_modal',
              as: :result_contents_modal
          post 'new/result_contents',
               to: 'reports#result_contents',
               as: :result_contents
          post '_save',
               to: 'reports#save_modal',
               as: :save_modal
        end
      end
      resources :experiments,
                only: [:new, :create, :edit, :update],
                defaults: { format: 'json' }
      member do
        # Notifications popup for individual project in projects index
        get 'notifications'
        # get 'samples' # Samples for single project
        # Renders sample datatable for single project (ajax action)
        # post 'samples_index'
        get 'experiment_archive' # Experiment archive for single project
        # post :delete_samples,
        #      constraints: CommitParamRouting.new(
        #        ProjectsController::DELETE_SAMPLES
        #      ),
        #      action: :delete_samples
      end

      # This route is defined outside of member block
      # to preserve original :project_id parameter in URL.
      get 'users/edit', to: 'user_projects#index_edit'
    end

    resources :experiments do
      member do
        get 'canvas' # Overview/structure for single experiment
        # AJAX-loaded canvas edit mode (from canvas)
        get 'canvas/edit', to: 'canvas#edit'
        get 'canvas/full_zoom', to: 'canvas#full_zoom' # AJAX-loaded canvas zoom
        # AJAX-loaded canvas zoom
        get 'canvas/medium_zoom', to: 'canvas#medium_zoom'
        get 'canvas/small_zoom', to: 'canvas#small_zoom' # AJAX-loaded canvas zoom
        post 'canvas', to: 'canvas#update' # Save updated canvas action
        get 'module_archive' # Module archive for single experiment
        get 'my_module_tags', to: 'my_module_tags#canvas_index'
        get 'archive' # archive experiment
        get 'clone_modal' # return modal with clone options
        post 'clone' # clone experiment
        get 'move_modal' # return modal with move options
        post 'move' # move experiment
        # get 'samples' # Samples for single project
        get 'updated_img' # Checks if the workflow image is updated
        get 'fetch_workflow_img' # Get udated workflow img
        # Renders sample datatable for single project (ajax action)
      #   post 'samples_index'
      #   post :delete_samples,
      #        constraints: CommitParamRouting.new(
      #          ExperimentsController::DELETE_SAMPLES
      #        ),
      #        action: :delete_samples
      end
    end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  include SearchableModel
  include SearchableByNameModel
  include RepositoryImportParser
  include Discard::Model

  enum permission_level: Extends::SHARED_INVENTORIES_PERMISSION_LEVELS

  attribute :discarded_by_id, :integer

  belongs_to :team
  belongs_to :created_by, foreign_key: :created_by_id, class_name: 'User'
  has_many :repository_columns, dependent: :destroy
  has_many :repository_rows, dependent: :destroy
  has_many :repository_table_states,
           inverse_of: :repository, dependent: :destroy
  has_many :report_elements, inverse_of: :repository, dependent: :destroy
  has_many :repository_list_items, inverse_of: :repository, dependent: :destroy
  has_many :repository_checklist_items, inverse_of: :repository, dependent: :destroy
  has_many :team_repositories, inverse_of: :repository, dependent: :destroy
  has_many :teams_shared_with, through: :team_repositories, source: :team

  auto_strip_attributes :name, nullify: false
  validates :name,
            presence: true,
            uniqueness: { scope: :team_id, case_sensitive: false },
            length: { maximum: Constants::NAME_MAX_LENGTH }
  validates :team, presence: true
  validates :created_by, presence: true

  default_scope -> { kept }
  scope :accessible_by_teams, lambda { |teams|
    left_outer_joins(:team_repositories)
      .where('repositories.team_id IN (?) '\
             'OR team_repositories.team_id IN (?) '\
             'OR repositories.permission_level = ? '\
             'OR repositories.permission_level = ? ',
             teams,
             teams,
             Extends::SHARED_INVENTORIES_PERMISSION_LEVELS[:shared_read],
             Extends::SHARED_INVENTORIES_PERMISSION_LEVELS[:shared_write])
      .distinct
  }

  scope :used_on_task_but_unshared, lambda { |task, team|
    where(id: task.repository_rows
      .select(:repository_id))
      .where.not(id: accessible_by_teams(team.id).select(:id)).distinct
  }

  def self.search(
    user,
    query = nil,
    page = 1,
    repository = nil,
    options = {}
  )
    repositories = repository&.id || Repository.accessible_by_teams(user.teams.pluck(:id)).pluck(:id)

    readable_rows = RepositoryRow.joins(:repository).where(repository_id: repositories)

    matched_by_user = readable_rows.joins(:created_by).where_attributes_like('users.full_name', query, options)

    repository_row_matches =
      readable_rows.where_attributes_like(['repository_rows.name', 'repository_rows.id'], query, options)

    repository_rows = readable_rows.where(id: repository_row_matches)
    repository_rows = repository_rows.or(readable_rows.where(id: matched_by_user))

    Extends::REPOSITORY_EXTRA_SEARCH_ATTR.each do |field, include_hash|
      custom_cell_matches = readable_rows.joins(repository_cells: include_hash)
                                         .where_attributes_like(field, query, options)
      repository_rows = repository_rows.or(readable_rows.where(id: custom_cell_matches))
    end

    # Show all results if needed
    if page == Constants::SEARCH_NO_LIMIT
      repository_rows.select('repositories.id AS id, COUNT(DISTINCT repository_rows.id) AS counter')
                     .group('repositories.id')
    else
      repository_rows.limit(Constants::SEARCH_LIMIT)
                     .offset((page - 1) * Constants::SEARCH_LIMIT)
    end
  end

  def i_shared?(team)
    shared_with_anybody? && self.team == team
  end

  def shared_with_anybody?
    (!not_shared? || team_repositories.any?)
  end

  def shared_with?(team)
    return false if self.team == team

    !not_shared? || private_shared_with?(team)
  end

  def shared_with_write?(team)
    return false if self.team == team

    shared_write? || private_shared_with_write?(team)
  end

  def shared_with_read?(team)
    return false if self.team == team

    shared_read? || team_repositories.where(team: team, permission_level: :shared_read).any?
  end

  def private_shared_with?(team)
    team_repositories.where(team: team).any?
  end

  def private_shared_with_write?(team)
    team_repositories.where(team: team, permission_level: :shared_write).any?
  end

  def self.viewable_by_user(_user, teams)
    where(team: teams)
  end

  def self.name_like(query)
    where('repositories.name ILIKE ?', "%#{query}%")
  end

  def available_columns_ids
    repository_columns.pluck(:id)
  end

  def importable_repository_fields
    fields = {}
    # First and foremost add record name
    fields['-1'] = I18n.t('repositories.default_column')
    # Add all other custom columns
    repository_columns.order(:created_at).each do |rc|
      next unless rc.importable?

      fields[rc.id] = rc.name
    end
    fields
  end

  def copy(created_by, name)
    new_repo = nil

    begin
      Repository.transaction do
        # Clone the repository object
        new_repo = dup
        new_repo.created_by = created_by
        new_repo.name = name
        new_repo.save!

        # Clone columns (only if new_repo was saved)
        repository_columns.find_each do |col|
          new_col = col.dup
          new_col.repository = new_repo
          new_col.created_by = created_by
          new_col.save!
        end
      end
    rescue ActiveRecord::RecordInvalid
      return false
    end

    # If everything is okay, return new_repo
    Activities::CreateActivityService
      .call(activity_type: :copy_inventory,
            owner: created_by,
            subject: new_repo,
            team: new_repo.team,
            message_items: { repository_new: new_repo.id, repository_original: id })

    new_repo
  end

  def cell_preload_includes
    cell_includes = []
    repository_columns.pluck(:data_type).each do |data_type|
      cell_includes << data_type.constantize::PRELOAD_INCLUDE
    end
    cell_includes
  end

  def import_records(sheet, mappings, user)
    importer = RepositoryImportParser::Importer.new(sheet, mappings, user, self)
    importer.run
  end

  def destroy_discarded(discarded_by_id = nil)
    self.discarded_by_id = discarded_by_id
    destroy
  end
  handle_asynchronously :destroy_discarded,
                        queue: :clear_discarded_repository,
                        priority: 20
end

app/views/repositories/_export_repository_modal.html.erb
<div class="modal fade"
     id="exportRepositoryModal"
     tabindex="-1"
     role="dialog"
     aria-labelledby="modal-export-repository-label">
  <%= bootstrap_form_tag(url: export_repository_team_path(repository),
                         html: { id: 'form-export' },
                         remote: true) do |f| %>
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title"><%=t 'zip_export.modal_label' %></h4>
         </div>
         <div class="modal-body">
           <div><%=t('zip_export.repository_header_html', repository: repository.name) %></div>
           <div class="custom-alert-info"><%=t 'zip_export.files_alert' %></div>
           <div><%=t 'zip_export.repository_footer_html' %></div>
         </div>
         <div class="modal-footer">
           <button type='button' class='btn btn-default' data-dismiss='modal' id='close-modal-export-repositories'><%= t('general.cancel')%></button>
           <%= f.submit t('my_modules.repository.export'), id: "export-repositories", class: "btn btn-success" %>
         </div>
       </div>
     </div>
   <% end %>
</div>

app/views/repositories/_repository_table.html.erb
<div class="repository-table">
  <table id="repository-table-<%= repository.id %>" class="table"
    data-current-uri="<%= request.original_url %>"
    data-repository-id="<%= repository.id %>"
    data-source="<%= repository_index_link %>"
    data-num-columns="<%= 6 + repository.repository_columns.count %>"
    data-create-record="<%= repository_repository_rows_path(repository) %>"
    data-delete-record="<%= repository_delete_records_path(repository) %>"
    data-copy-records="<%= repository_copy_records_path(repository) %>"
    data-direct-upload-url="<%= rails_direct_uploads_url %>"
    data-max-dropdown-length="<%= Constants::MODAL_TEXT_MAX_LENGTH %>"
    data-repository-columns-ids="<%= repository.available_columns_ids %>"
    data-save-text="<%= I18n.t('general.save') %>"
    data-edit-text="<%= I18n.t('general.edit') %>"
    data-cancel-text="<%= I18n.t('general.cancel') %>"
    data-columns-visibility-text="<%= I18n.t('repositories.columns_visibility') %>"
    data-columns-delete-text="<%= I18n.t('repositories.columns_delete') %>"
    data-available-columns="<%= repository_available_columns_path(repository) %>"
    data-columns-changed="<%= I18n.t('repositories.columns_changed') %>"
    data-default-order="<%= default_table_order_as_js_array %>"
    data-default-table-columns="<%= default_table_columns %>"
    data-editable="<%= can_manage_repository_rows?(repository) %>">
    <thead>
      <tr>
        <th id="checkbox">
            <input name="select_all" value="1" type="checkbox" class="sci-checkbox">
            <span class="sci-checkbox-label"></span>
        </th>
        <th id="assigned"><%= t("repositories.table.assigned") %></th>
        <th id="row-id"><%= t("repositories.table.id") %></th>
        <th id="row-name"><%= t("repositories.table.row_name") %></th>
        <th id="added-on"><%= t("repositories.table.added_on") %></th>
        <th id="added-by"><%= t("repositories.table.added_by") %></th>
        <% repository.repository_columns.order(:id).each do |column| %>
          <th
            class="repository-column"
            id="<%= column.id %>"
            data-type="<%= column.data_type %>"
            data-edit-column-url="<%= edit_repository_repository_column_path(repository, column) %>"
            data-destroy-column-url="<%= repository_columns_destroy_html_path(repository, column) %>"
            data-editable-row="<%= can_manage_repository_column?(column) %>"
            <% column.metadata.each do |k, v| %>
              <%= "data-metadata-#{k}=#{v}" %>
            <% end %>
            <%= "data-items-url=#{items_repository_repository_columns_checklist_column_path(repository, column)}" if column.repository_checklist_value? %>
            <%= "data-items-url=#{items_repository_repository_columns_list_column_path(repository, column)}" if column.repository_list_value? %>
            <%= "data-items-url=#{items_repository_repository_columns_status_column_path(repository, column)}" if column.repository_status_value? %>
          >
            <%= display_tooltip(column.name) %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>

app/views/repositories/_sidebar.html.erb
 <%= content_for :sidebar do %>
  <div id="slide-panel" class="visible">
    <div id="repo-tree" class="tree">
      <ul>
        <% if can_create_repositories?(current_team) %>
          <li>
            <span class="tree-link no-indent">
              <a class="btn btn-secondary create-new-repository" data-remote="true"
                 href="<%= create_modal_team_repositories_path(current_team) %>">
                <i class="fas fa-plus"></i>
                <%= t('libraries.index.no_libraries.create_new_button') %>
              </a>
            </span>
          </li>
        <% end %>
        <% repositories.each do |repository| %>
          <li class="<%= 'active parent_li' if current_page?(repository_path(repository)) %>" >
            <span class="tree-link no-indent" title="<%= repository.name %>">
              <%= link_to repository.name,
                          repository_path(repository),
                          class: current_page?(repository_path(repository)) ? 'disabled line-wrap' : 'line-wrap',
                          data: { 'no-turbolink' => 'true', type: 'repository', id: repository.id } %>
              <%= inventory_shared_status_icon(repository, current_team) %>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<script>
  $('#wrapper').show();
</script>

app/views/repositories/show.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<% provide(:head_title, t("libraries.show.head_title", library: @repository.name)) %>
<%= stylesheet_link_tag 'datatables' %>
<% provide(:container_class, "no-second-nav-container") %>

<%= render partial: "sidebar", locals: { repositories: @repositories } %>
<div id="alert-container"></div>

<div class="content-pane repository-show" data-table-url="<%= load_table_repository_path(@repository) %> ">
  <div id="repository-toolbar">
    <div class="repository-title-name">
      <h2 class="name-container">
        <% if @inline_editable_title_config.present? %>
          <%= render partial: "shared/inline_editing",
                     locals: {
                        initial_value: @repository.name,
                        config: @inline_editable_title_config
                     } %>
        <% else %>
          <div class="read-only-name">
            <%= @repository.name %>
          </div>
          <span class="repository-share-icon">
            <%= inventory_shared_status_icon(@repository, current_team) %>
          </span>
        <% end %>
      </h2>
      <% if @repository.shared_with_anybody? %>
        <% team_name = @repository.team == current_team ? 'your Team' : @repository.team.name %>
        <div class="repository-subtitle"><%= t('repositories.subtitle', team_name: team_name) %></div>
      <% end %>
    </div>
    <div class="repo-datatables-buttons">
      <div class="share-repository-button">
        <% if can_share_repository?(@repository) && current_user.teams.count > 1 %>
          <%= link_to team_repository_share_modal_path(current_team, repository_id: @repository),
                      class: 'btn btn-secondary share-repo-option', remote: true, id: 'shareRepoBtn' do %>
            <span class="fas fa-user-plus"></span>
            <span class="hidden-xs"><%= t('repositories.index.share_inventory') %></span>
          <% end %>
        <% end %>
      </div>

      <button class="btn btn-secondary help_tooltips manage-repo-column-index"
              data-modal-url="<%= repository_columns_index_html_path(@repository) %>"
              data-action="new"
              data-tooltiplink="<%= I18n.t('tooltips.link.inventory.manage_columns') %>"
              data-tooltipcontent="<%= I18n.t('tooltips.text.inventory.manage_columns') %>">
        <span class="fas fa-wrench"></span>&nbsp;<%= t('repositories.index.columns') %>
      </button>

      <div class="repository-cog dropdown">
        <button id="repository-acitons-dropdown"
                class="btn btn-secondary"
                type="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="true"
                <%= "disabled" unless can_perform_repository_actions(@repository) %>>
          <span class="fas fa-pencil-alt"></span>
          <span class="hidden-xs"><%= t('repositories.index.edit_inventory') %></span>
          <span class="caret"></span>
        </button>

        <% if can_perform_repository_actions(@repository) %>
          <ul class="dropdown-menu pull-right">
            <% if can_create_repository_rows?(@repository) %>
              <li>
                <a href="#" id="importRecordsButton" data-turbolinks="false">
                  <%= t('repositories.index.options_dropdown.import_items') %>
                </a>
              <li>
            <% end %>
            <% if can_read_repository?(@repository) %>
              <li>
                <a href="#"  id="exportRepositoriesButton" data-turbolinks="false">
                  <%= t("repositories.index.options_dropdown.export_items") %>
                </a>
              </li>
            <% end %>
            <% if can_create_repositories?(current_team) && !@repository.shared_with?(current_team) %>
              <li>
                <%= link_to t('repositories.index.options_dropdown.copy'),
                            team_repository_copy_modal_path(current_team, repository_id: @repository),
                            class: "copy-repo-option",
                            remote: true %>
              </li>
            <% end %>
            <% if can_manage_repository?(@repository) %>
              <li data-hook="destroy-repository-option" role="separator" class="divider"></li>
              <li data-hook="destroy-repository-option">
                <%= link_to t('repositories.index.options_dropdown.delete'),
                            team_repository_destroy_modal_path(current_team, repository_id: @repository),
                            class: "delete-repo-option",
                            remote: true %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>

    <div class="toolbar-delimiter"></div>
  </div>

  <!-- These buttons are appended to table in javascript, after table initialization -->
  <div class="toolbar-filter-buttons" style="display:none">
  </div>

  <div class="toolbarButtonsDatatable" style="display:none">

    <% if can_create_repository_rows?(@repository) %>
      <button type="button" class="btn btn-primary editAdd help_tooltips"
              id="addRepositoryRecord" onclick="onClickAddRecord()"
              data-tooltiplink="<%= I18n.t('tooltips.link.inventory.new') %>"
              data-tooltipcontent="<%= I18n.t('tooltips.text.inventory.new') %>">
        <span class="fas fa-plus"></span>
        <span class="hidden-xs"><%= t("repositories.add_new_record") %></span>
      </button>
    <% end %>

    <% if can_manage_repository_rows?(@repository) %>
      <span id="editDeleteCopy" data-toggle="buttons" style="display:none">
        <%if @display_edit_button %>
          <button type="button" class="btn btn-light editAdd" id="editRepositoryRecord" onclick="onClickEdit()" disabled>
            <span class="fas fa-pencil-alt"></span>
            <span class="hidden-xs-custom"><%= t("repositories.edit_record") %></span>
          </button>
        <% end %>

        <%if @display_delete_button %>
          <button type="button" class="btn btn-light"
            id="deleteRepositoryRecordsButton" onclick="onClickDelete()" disabled>
            <span class="fas fa-trash"></span>
            <span class="hidden-xs-custom"><%= t'repositories.delete_record' %></span>
            <%= submit_tag I18n.t('repositories.delete_record'), :class => "hidden delete_repository_records_submit" %>
          </button>
        <% end %>

        <%if @display_duplicate_button %>
          <button type="button" class="btn btn-light copyRow" id="copyRepositoryRecords" onclick="onClickCopyRepositoryRecords()" disabled>
            <span class="fas fa-copy"></span>
            <span class="hidden-xs-custom"><%= t("repositories.copy_record") %></span>
          </button>
        <%end%>
      </span>

      <span id="saveCancel" data-toggle="buttons" style="display:none">
        <button type="button" class="btn btn-success" id="saveRecord">
          <span class="fas fa-save"></span>
          <%= t("repositories.save_record") %>
        </button>
        <button type="button" class="btn btn-light" id="cancelSave">
          <span class="fas fa-times-circle"></span>
          <%= t("repositories.cancel_save") %>
        </button>
      </span>
    <% elsif @repository.shared_with?(current_team) %>
      <p class="view-only-label"><%= t('repositories.index.view_only_permission_label') %></p>
    <% end %>
  </div>

  <%= render partial: "repositories/repository_table.html.erb",
             locals: {
               repository: @repository,
               repository_index_link: repository_table_index_path(@repository)
             }
  %>
</div>

<%= render partial: 'repositories/import_repository_records_modal.html.erb',
                    locals: { repository: @repository } %>

<%= render partial: "repositories/delete_record_modal.html.erb" %>
<%= render partial: 'repositories/export_repository_modal.html.erb',
           locals: { repository: @repository } %>

<%= render partial: 'repository_columns/manage_column_modal.html.erb', locals: { my_module_page: false } %>

<%= javascript_include_tag 'repositories/edit' %>
<%= javascript_include_tag 'repositories/repository_datatable' %>
<%= javascript_include_tag "repositories/show" %>
<%= javascript_include_tag "repositories/index" %>
<%= javascript_pack_tag 'custom/inputmask' %>
<%= javascript_pack_tag 'emoji_button' %>

<script type="text/javascript" charset="utf-8">
  <%
    js_format = I18n.backend.date_format.dup
    js_format.gsub!(/%-d/, 'D')
    js_format.gsub!(/%d/, 'DD')
    js_format.gsub!(/%-m/, 'M')
    js_format.gsub!(/%m/, 'MM')
    js_format.gsub!(/%b/, 'MMM')
    js_format.gsub!(/%B/, 'MMMM')
    js_format.gsub!('%Y', 'YYYY')
  %>

  var formatJS = "<%= js_format %>"
</script>