config/routes.rb
    get 'users/settings/user_teams/:id/leave_html',
        to: 'users/settings/user_teams#leave_html',
        as: 'leave_user_team_html'
    get 'users/settings/user_teams/:id/destroy_html',
        to: 'users/settings/user_teams#destroy_html',
        as: 'destroy_user_team_html'
    delete 'users/settings/user_teams/:id',
           to: 'users/settings/user_teams#destroy',
           as: 'destroy_user_team'

    # Invite users
    devise_scope :user do
      post '/invite',
           to: 'users/invitations#invite_users',
           as: 'invite_users'
    end

    # Notifications
    get 'users/:id/recent_notifications',
        to: 'user_notifications#recent_notifications',
        as: 'recent_notifications',
        defaults: { format: 'json' }

    get 'users/:id/unseen_notification',
        to: 'user_notifications#unseen_notification',
        as: 'unseen_notification',
        defaults: { format: 'json' }

    get 'users/notifications',
        to: 'user_notifications#index',
        as: 'notifications'

    # Get Zip Export
    get 'zip_exports/download/:id',
        to: 'zip_exports#download',
        as: 'zip_exports_download'

    # Get Team Zip Export
    get 'zip_exports/download_export_all_zip/:id',
        to: 'zip_exports#download_export_all_zip',
        as: 'zip_exports_download_export_all'

    get 'zip_exports/file_expired',
        to: 'zip_exports#file_expired',
        as: 'file_expired'

    resources :teams do
      resources :repositories, only: %i(index create destroy update) do
        collection do
          get 'create_modal', to: 'repositories#create_modal',
              defaults: { format: 'json' }
        end
        get 'destroy_modal', to: 'repositories#destroy_modal',
            defaults: { format: 'json' }
        get 'rename_modal', to: 'repositories#rename_modal',
            defaults: { format: 'json' }
        get 'copy_modal', to: 'repositories#copy_modal',
            defaults: { format: 'json' }
        post 'copy', to: 'repositories#copy',
             defaults: { format: 'json' }
        get :share_modal

        resources :team_repositories, only: %i(destroy) do
          collection do
            post 'update'
          end
        end
      end
      # resources :samples, only: [:new, :create]
      # resources :sample_types, except: [:show, :new] do
      #   get 'sample_type_element', to: 'sample_types#sample_type_element'
      #   get 'destroy_confirmation', to: 'sample_types#destroy_confirmation'
      # end
      # resources :sample_groups, except: [:show, :new] do
      #   get 'sample_group_element', to: 'sample_groups#sample_group_element'
      #   get 'destroy_confirmation', to: 'sample_groups#destroy_confirmation'
      # end
      # resources :custom_fields, only: [:create, :edit, :update, :destroy] do
      #   get 'destroy_html'
      # end
      member do
        post 'parse_sheet', defaults: { format: 'json' }
        post 'export_repository', to: 'repositories#export_repository'
        post 'export_projects'
        get 'export_projects_modal'
        # Used for atwho (smart annotations)
        get 'atwho_users', to: 'at_who#users'
        get 'atwho_repositories', to: 'at_who#repositories'
        get 'atwho_rep_items', to: 'at_who#rep_items'
        get 'atwho_projects', to: 'at_who#projects'
        get 'atwho_experiments', to: 'at_who#experiments'
        get 'atwho_my_modules', to: 'at_who#my_modules'
        get 'atwho_menu_items', to: 'at_who#menu_items'
      end

      # External protocols routes
      get 'list_external_protocol', to: 'external_protocols#index'
      get 'show_external_protocol', to: 'external_protocols#show'
      get 'build_external_protocol', to: 'external_protocols#new'
      post 'import_external_protocol', to: 'external_protocols#create'

      match '*path',
            to: 'teams#routing_error',
            via: [:get, :post, :put, :patch]
    end

    post 'projects/index_dt', to: 'projects#index_dt', as: 'projects_index_dt'
    get 'projects/sidebar', to: 'projects#sidebar', as: 'projects_sidebar'
    get 'projects/dt_state_load', to: 'projects#dt_state_load',
                                  as: 'projects_dt_state_load'

    resources :reports, only: :index
    get 'reports/datatable', to: 'reports#datatable'
    post 'reports/visible_projects', to: 'reports#visible_projects',
                                     defaults: { format: 'json' }
    post 'reports/available_repositories', to: 'reports#available_repositories',
                                           defaults: { format: 'json' }
    post 'reports/save_pdf_to_inventory_item',
         to: 'reports#save_pdf_to_inventory_item',
         defaults: { format: 'json' }
    post 'available_asset_type_columns',
          to: 'repository_columns#available_asset_type_columns',
          defaults: { format: 'json' }
    post 'reports/destroy', to: 'reports#destroy'

    resources :projects, except: [:new, :destroy] do
      resources :user_projects, path: '/users',
                only: [:create, :index, :update, :destroy]
      resources :project_comments,
                path: '/comments',
                only: [:create, :index, :edit, :update, :destroy]
      # Activities popup (JSON) for individual project in projects index,
      # as well as all activities page for single project (HTML)
      resources :project_activities, path: '/activities', only: [:index]
      resources :tags, only: [:create, :update, :destroy]
      resources :reports,
                path: '/reports',
                only: %i(edit update create) do
        collection do
          # The posts following here should in theory be gets,
          # but are posts because of parameters payload
          post 'generate', to: 'reports#generate', format: %w(docx pdf)
          get 'new/', to: 'reports#new'
          get 'new/project_contents_modal',
              to: 'reports#project_contents_modal',
              as: :project_contents_modal
          post 'new/project_contents',
               to: 'reports#project_contents',
               as: :project_contents
          get 'new/experiment_contents_modal',
              to: 'reports#experiment_contents_modal',
              as: :experiment_contents_modal
          post 'new/experiment_contents',
               to: 'reports#experiment_contents',
               as: :experiment_contents
          get 'new/module_contents_modal',
              to: 'reports#module_contents_modal',
              as: :module_contents_modal
          post 'new/module_contents',
               to: 'reports#module_contents',
               as: :module_contents
          get 'new/step_contents_modal',
              to: 'reports#step_contents_modal',
              as: :step_contents_modal
          post 'new/step_contents',
               to: 'reports#step_contents',
               as: :step_contents
          get 'new/result_contents_modal',
              to: 'reports#result_contents_modal',
              as: :result_contents_modal
          post 'new/result_contents',
               to: 'reports#result_contents',
               as: :result_contents
          post '_save',
               to: 'reports#save_modal',
               as: :save_modal
        end
      end
      resources :experiments,
                only: [:new, :create, :edit, :update],
                defaults: { format: 'json' }
      member do
        # Notifications popup for individual project in projects index
        get 'notifications'
        # get 'samples' # Samples for single project
        # Renders sample datatable for single project (ajax action)
        # post 'samples_index'
        get 'experiment_archive' # Experiment archive for single project
        # post :delete_samples,
        #      constraints: CommitParamRouting.new(
        #        ProjectsController::DELETE_SAMPLES
        #      ),
        #      action: :delete_samples
      end

      # This route is defined outside of member block
      # to preserve original :project_id parameter in URL.
      get 'users/edit', to: 'user_projects#index_edit'
    end

    resources :experiments do
      member do
        get 'canvas' # Overview/structure for single experiment
        # AJAX-loaded canvas edit mode (from canvas)
        get 'canvas/edit', to: 'canvas#edit'
        get 'canvas/full_zoom', to: 'canvas#full_zoom' # AJAX-loaded canvas zoom
        # AJAX-loaded canvas zoom
        get 'canvas/medium_zoom', to: 'canvas#medium_zoom'
        get 'canvas/small_zoom', to: 'canvas#small_zoom' # AJAX-loaded canvas zoom
        post 'canvas', to: 'canvas#update' # Save updated canvas action
        get 'module_archive' # Module archive for single experiment
        get 'my_module_tags', to: 'my_module_tags#canvas_index'
        get 'archive' # archive experiment
        get 'clone_modal' # return modal with clone options
        post 'clone' # clone experiment
        get 'move_modal' # return modal with move options
        post 'move' # move experiment
        # get 'samples' # Samples for single project
        get 'updated_img' # Checks if the workflow image is updated
        get 'fetch_workflow_img' # Get udated workflow img
        # Renders sample datatable for single project (ajax action)
      #   post 'samples_index'
      #   post :delete_samples,
      #        constraints: CommitParamRouting.new(
      #          ExperimentsController::DELETE_SAMPLES
      #        ),
      #        action: :delete_samples
      end
    end

    # Show action is a popup (JSON) for individual module in full-zoom canvas,
    # as well as 'module info' page for single module (HTML)
    resources :my_modules, path: '/modules', only: [:show, :update] do
      resources :my_module_tags, path: '/tags', only: [:index, :create, :destroy] do
        collection do
          get :search_tags
        end
        member do
          post :destroy_by_tag_id
        end
      end
      resources :user_my_modules, path: '/users',

app/controllers/api/v1/experiments_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ExperimentsController < BaseController
      before_action :load_team
      before_action :load_project
      before_action only: :show do
        load_experiment(:id)
      end

      def index
        experiments = @project.experiments
                              .page(params.dig(:page, :number))
                              .per(params.dig(:page, :size))
        render jsonapi: experiments, each_serializer: ExperimentSerializer
      end

      def show
        render jsonapi: @experiment, serializer: ExperimentSerializer
      end
    end
  end
end

app/views/experiments/_clone_modal.html.erb
<!-- Clone experiment modal -->
<div class="modal"
     id="clone-experiment-modal-<%= @experiment.id %>"
     tabindex="-1"
     role="dialog"
     aria-labelledby="clone-experiment-modal-label">
     <%= bootstrap_form_for @experiment, url: clone_experiment_path(),
                            method: :post do |f| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="clone-experiment-modal-label"><%= t("experiments.clone.modal_title", experiment: @experiment.name ) %></h5>
        </div>
        <div class="modal-body">
          <%= f.select :project_id,
                       options_for_select(
                         @projects.collect do |p|
                           if p == @experiment.project
                             [ "#{p.name} #{t('experiments.clone.current_project')}", p.id ]
                           else
                             [ p.name, p.id ]
                           end
                         end,
                         @project.id ),
                       {}, {class: "form-control selectpicker", "data-role" => "clear"} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><%=t "general.cancel" %></button>
          <%= f.submit t("experiments.clone.modal_submit"), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/experiments/_dropdown_actions.html.erb
<ul class="dropdown-menu dropdown-experiment-actions"
  aria-labelledby="exActionsMenu-<%= experiment.id %>"
  data-id="<%= experiment.id %>">

  <% if can_manage_experiment?(experiment) %>
  <li><%= link_to t('experiments.edit.label_title'),
                edit_project_experiment_url(project, experiment),
                remote: true,
                type: 'button',
                data: { id: experiment.id },
                class: 'edit-experiment' %></li>
  <% end %>
  <li data-hook="experiment-actions-second-child"></li>
  <% if can_clone_experiment?(experiment) %>
    <li><%= link_to t('experiments.clone.label_title'),
                    clone_modal_experiment_url(experiment),
                    remote: true, type: 'button',
                    class: 'clone-experiment help_tooltips',
                    data: {
                      tooltiplink: I18n.t('tooltips.link.experiment.copy'),
                      tooltipcontent: I18n.t('tooltips.text.experiment.copy')
                    } %></li>
  <% end %>
  <% if can_move_experiment?(experiment) %>
    <li><%= link_to t('experiments.move.label_title'),
                    move_modal_experiment_url(experiment),
                    remote: true, type: 'button',
                    class: 'move-experiment help_tooltips',
                    data: {
                      tooltiplink: I18n.t('tooltips.link.experiment.move'),
                      tooltipcontent: I18n.t('tooltips.text.experiment.move')
                    } %></li>
  <% end %>
  <% if can_archive_experiment?(experiment) %>
  <li><%= link_to t('experiments.archive.label_title'),
                archive_experiment_url(experiment),
                type: 'button',
                data: { confirm: t('experiments.canvas.archive_confirm') } %></li>
  <% end %>
</ul>

app/views/experiments/_edit_modal.html.erb
<!-- Edit experiment modal -->
<div class="modal"
     id="edit-experiment-modal-<%= @experiment.id %>"
     tabindex="-1"
     role="dialog"
     aria-labelledby="edit-experiment-modal-label">
  <%= bootstrap_form_for [@project, @experiment], remote: true do |f| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="edit-eperiment-modal-label"><%= t("experiments.edit.modal_title", experiment: @experiment.name ) %></h4>
        </div>
        <div class="modal-body">
          <%= render partial: "form.html.erb", locals: { form: f } %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><%=t "general.cancel" %></button>
          <%= f.submit t("experiments.edit.modal_create"), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/experiments/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div  class="form-group">
      <%= form.text_field :name,
                          label: t("experiments.new.name"),
                          autofocus: true,
                          placeholder: t("experiments.new.name_placeholder"),
                          id: 'experiment-name'%>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="form-group">
      <%= form.smart_text_area :description,
                               label: t('experiments.new.description'),
                               id: 'experiment-description',
                               data: { 'atwho-edit' => '' } %>
    </div>
  </div>
</div>

app/views/experiments/_move_modal.html.erb
<!-- Move experiment modal -->
<div class="modal"
     id="move-experiment-modal-<%= @experiment.id %>"
     tabindex="-1"
     role="dialog"
     aria-labelledby="move-experiment-modal-label">
     <%= bootstrap_form_for @experiment, url: move_experiment_path(),
                            method: :post,
                            remote: true do |f| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="move-experiment-modal-label"><%= t("experiments.move.modal_title", experiment: @experiment.name ) %></h5>
        </div>
        <div class="modal-body">
          <% if !@projects.blank? %>
            <%= f.select :project_id, options_for_select(@projects.collect { |p| [ p.name, p.id ] }),
                        {}, { class: "form-control selectpicker", "data-role" => "clear" } %>
          <% else %>
            <div>
              <em>
                <%= t("experiments.move.no_projects") %>
              </em>
            </div>
          <% end %>
          <%= t("experiments.move.notice") %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><%=t "general.cancel" %></button>
          <% if !@projects.blank? %>
            <%= f.submit t("experiments.move.modal_submit"), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/experiments/_new_modal.html.erb
<!-- New experiment modal -->
<div class="modal" id="new-experiment-modal" tabindex="-1" role="dialog" aria-labelledby="new-experiment-modal-label">
  <%= bootstrap_form_for [@project, @experiment], remote: true do |f| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="new-eperiment-modal-label"><%= t("experiments.new.modal_title") %></h4>
        </div>
        <div class="modal-body">
          <%= render partial: "form.html.erb", locals: { form: f } %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><%=t "general.cancel" %></button>
          <%= f.submit t("experiments.new.modal_create"), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/experiments/canvas.html.erb
<% provide(:head_title, t("experiments.canvas.head_title", project: h(@project.name)).html_safe) %>
<%= render partial: "shared/sidebar", locals: { current_experiment: @experiment, page: 'canvas' } %>
<%= render partial: "shared/secondary_navigation" %>

<div class="content-pane" id="experiment-canvas">
  <div class="row">
    <div class="container-fluid">
      <div id="diagram-buttons">
        <% if can_manage_experiment?(@experiment) %>
          <%=link_to canvas_edit_experiment_url(@experiment),
                remote: true,
                type: 'button',
                id: 'edit-canvas-button',
                data: { action: 'edit' },
                class: 'ajax btn btn-primary' do %>
                  <span class="fas fa-pencil-alt"></span>
                  <span class="hidden-xs"><%=t 'experiments.canvas.canvas_edit' %></span>
                <% end %>
          <!-- experiment actions -->
          <span class="dropdown actions-button">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="exActionsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <span class="hidden-xs"><%= t'experiments.canvas.actions' %></span>
              <span class="visible-xs-inline"><i class="fas fa-sort"></i></span>
              <span class="caret"></span>
            </button>
            <%= render partial: 'experiments/dropdown_actions.html.erb',
                                locals: { project: @project, experiment: @experiment } %>
          </span>
        <% end %>
        <div class="toolbarButtons">
          <span class="hidden-xs zoom-text"><%=t 'experiments.canvas.zoom' %></span>
          <div id="zoom-level-buttons" class="sci-toggles-group change-canvas-view" data-toggle="buttons">
            <input type="radio" name="canvas-format" class="sci-toggle-item" checked>
            <%=link_to canvas_full_zoom_experiment_path(@experiment), remote: true, type: "button", class: "ajax sci-toggle-item-label", "data-action" => "full_zoom", "data-toggle" => "button", "aria-pressed" => true do %>
              <span class="fas fa-th-large" aria-hidden="true" ></span>
            <% end %>
            <input type="radio" name="canvas-format" class="sci-toggle-item" >
            <%=link_to canvas_medium_zoom_experiment_path(@experiment), remote: true, type: "button", class: "ajax sci-toggle-item-label", "data-action" => "medium_zoom" do %>
              <span class="fas fa-th-list" aria-hidden="true"></span>
            <% end %>
            <input type="radio" name="canvas-format" class="sci-toggle-item" >
            <%=link_to canvas_small_zoom_experiment_path(@experiment), remote: true, type: "button", class: "ajax sci-toggle-item-label", "data-action" => "small_zoom" do %>
              <span class="fas fa-th" aria-hidden="true"></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="canvas-container" data-project-id="<%= @project.id %>" data-module-tags-url="<%= my_module_tags_experiment_path(@experiment, format: :json) %>">
    <%= render partial: 'canvas/full_zoom', locals: { experiment: @experiment, my_modules: @active_modules } %>
  </div>
</div>

<!-- Manage tags modal -->
<%= render partial: "my_modules/modals/manage_module_tags_modal", locals: { my_module: nil } %>

<!-- Initialize dropdown actions -->
<%= javascript_include_tag("experiments/dropdown_actions") %>

<!-- Include all the neccesary JS libraries -->
<%= javascript_include_tag("eventPause-min") %>

<%= javascript_include_tag("projects/canvas") %>

app/views/experiments/module_archive.html.erb
<% provide(:head_title, t("experiments.module_archive.head_title", experiment: h(@experiment.name)).html_safe) %>
<%= render partial: "shared/sidebar", locals: { current_experiment: @experiment, page: 'experiment' } %>
<%= render partial: "shared/secondary_navigation" %>

<div class="content-pane" id="module-archive">
  <% if @experiment.archived_modules.count > 0 %>
    <div class="row" style="margin-top: 10px;">
      <% @experiment.archived_modules.each_with_index do |my_module, i| %>
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
          <%= render partial: "experiments/module_archive/my_module.html.erb", locals: { my_module: my_module} %>
        </div>
        <% if (i+1) % 6 == 0 %>
        <div class="clearfix visible-lg-block"></div>
        <% end %>
        <% if (i+1) % 4 == 0 %>
        <div class="clearfix visible-md-block"></div>
        <% end %>
        <% if (i+1) % 3 == 0 %>
        <div class="clearfix visible-sm-block"></div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="row">
      <div class="col-xs-12">
        <em><%=t "experiments.module_archive.no_archived_modules" %></em>
      </div>
    </div>
  <% end %>
</div>

app/views/experiments/samples.html.erb
<% provide(:head_title, t("projects.samples.head_title", project: h(@experiment.name)).html_safe) %>
<%= render partial: "shared/sidebar" %>
<%= render partial: "shared/secondary_navigation" %>

<div id="content">
  <%#= render partial: "shared/samples" %>
</div>