config/routes.rb
        defaults: { format: 'json' }

    get 'users/notifications',
        to: 'user_notifications#index',
        as: 'notifications'

    # Get Zip Export
    get 'zip_exports/download/:id',
        to: 'zip_exports#download',
        as: 'zip_exports_download'

    # Get Team Zip Export
    get 'zip_exports/download_export_all_zip/:id',
        to: 'zip_exports#download_export_all_zip',
        as: 'zip_exports_download_export_all'

    get 'zip_exports/file_expired',
        to: 'zip_exports#file_expired',
        as: 'file_expired'

    resources :teams do
      resources :repositories, only: %i(index create destroy update) do
        collection do
          get 'create_modal', to: 'repositories#create_modal',
              defaults: { format: 'json' }
        end
        get 'destroy_modal', to: 'repositories#destroy_modal',
            defaults: { format: 'json' }
        get 'rename_modal', to: 'repositories#rename_modal',
            defaults: { format: 'json' }
        get 'copy_modal', to: 'repositories#copy_modal',
            defaults: { format: 'json' }
        post 'copy', to: 'repositories#copy',
             defaults: { format: 'json' }
        get :share_modal

        resources :team_repositories, only: %i(destroy) do
          collection do
            post 'update'
          end
        end
      end
      # resources :samples, only: [:new, :create]
      # resources :sample_types, except: [:show, :new] do
      #   get 'sample_type_element', to: 'sample_types#sample_type_element'
      #   get 'destroy_confirmation', to: 'sample_types#destroy_confirmation'
      # end
      # resources :sample_groups, except: [:show, :new] do
      #   get 'sample_group_element', to: 'sample_groups#sample_group_element'
      #   get 'destroy_confirmation', to: 'sample_groups#destroy_confirmation'
      # end
      # resources :custom_fields, only: [:create, :edit, :update, :destroy] do
      #   get 'destroy_html'
      # end
      member do
        post 'parse_sheet', defaults: { format: 'json' }
        post 'export_repository', to: 'repositories#export_repository'
        post 'export_projects'
        get 'export_projects_modal'
        # Used for atwho (smart annotations)
        get 'atwho_users', to: 'at_who#users'
        get 'atwho_repositories', to: 'at_who#repositories'
        get 'atwho_rep_items', to: 'at_who#rep_items'
        get 'atwho_projects', to: 'at_who#projects'
        get 'atwho_experiments', to: 'at_who#experiments'
        get 'atwho_my_modules', to: 'at_who#my_modules'
        get 'atwho_menu_items', to: 'at_who#menu_items'
      end

      # External protocols routes
      get 'list_external_protocol', to: 'external_protocols#index'
      get 'show_external_protocol', to: 'external_protocols#show'
      get 'build_external_protocol', to: 'external_protocols#new'
      post 'import_external_protocol', to: 'external_protocols#create'

      match '*path',
            to: 'teams#routing_error',
            via: [:get, :post, :put, :patch]
    end

    post 'projects/index_dt', to: 'projects#index_dt', as: 'projects_index_dt'
    get 'projects/sidebar', to: 'projects#sidebar', as: 'projects_sidebar'
    get 'projects/dt_state_load', to: 'projects#dt_state_load',
                                  as: 'projects_dt_state_load'

    resources :reports, only: :index
    get 'reports/datatable', to: 'reports#datatable'
    post 'reports/visible_projects', to: 'reports#visible_projects',
                                     defaults: { format: 'json' }
    post 'reports/available_repositories', to: 'reports#available_repositories',
                                           defaults: { format: 'json' }
    post 'reports/save_pdf_to_inventory_item',
         to: 'reports#save_pdf_to_inventory_item',
         defaults: { format: 'json' }
    post 'available_asset_type_columns',
          to: 'repository_columns#available_asset_type_columns',
          defaults: { format: 'json' }
    post 'reports/destroy', to: 'reports#destroy'

    resources :projects, except: [:new, :destroy] do
      resources :user_projects, path: '/users',
                only: [:create, :index, :update, :destroy]
      resources :project_comments,
                path: '/comments',
                only: [:create, :index, :edit, :update, :destroy]
      # Activities popup (JSON) for individual project in projects index,
      # as well as all activities page for single project (HTML)
      resources :project_activities, path: '/activities', only: [:index]
      resources :tags, only: [:create, :update, :destroy]
      resources :reports,
                path: '/reports',
                only: %i(edit update create) do
        collection do
          # The posts following here should in theory be gets,
          # but are posts because of parameters payload
          post 'generate', to: 'reports#generate', format: %w(docx pdf)
          get 'new/', to: 'reports#new'
          get 'new/project_contents_modal',
              to: 'reports#project_contents_modal',
              as: :project_contents_modal
          post 'new/project_contents',
               to: 'reports#project_contents',
               as: :project_contents
          get 'new/experiment_contents_modal',
              to: 'reports#experiment_contents_modal',
              as: :experiment_contents_modal
          post 'new/experiment_contents',
               to: 'reports#experiment_contents',
               as: :experiment_contents
          get 'new/module_contents_modal',
              to: 'reports#module_contents_modal',
              as: :module_contents_modal
          post 'new/module_contents',
               to: 'reports#module_contents',
               as: :module_contents
          get 'new/step_contents_modal',
              to: 'reports#step_contents_modal',
              as: :step_contents_modal
          post 'new/step_contents',
               to: 'reports#step_contents',
               as: :step_contents
          get 'new/result_contents_modal',
              to: 'reports#result_contents_modal',
              as: :result_contents_modal
          post 'new/result_contents',
               to: 'reports#result_contents',
               as: :result_contents
          post '_save',
               to: 'reports#save_modal',
               as: :save_modal
        end
      end
      resources :experiments,
                only: [:new, :create, :edit, :update],
                defaults: { format: 'json' }
      member do
        # Notifications popup for individual project in projects index
        get 'notifications'
        # get 'samples' # Samples for single project
        # Renders sample datatable for single project (ajax action)
        # post 'samples_index'
        get 'experiment_archive' # Experiment archive for single project
        # post :delete_samples,
        #      constraints: CommitParamRouting.new(
        #        ProjectsController::DELETE_SAMPLES
        #      ),
        #      action: :delete_samples
      end

      # This route is defined outside of member block
      # to preserve original :project_id parameter in URL.
      get 'users/edit', to: 'user_projects#index_edit'
    end

    resources :experiments do
      member do
        get 'canvas' # Overview/structure for single experiment
        # AJAX-loaded canvas edit mode (from canvas)
        get 'canvas/edit', to: 'canvas#edit'
        get 'canvas/full_zoom', to: 'canvas#full_zoom' # AJAX-loaded canvas zoom
        # AJAX-loaded canvas zoom
        get 'canvas/medium_zoom', to: 'canvas#medium_zoom'
        get 'canvas/small_zoom', to: 'canvas#small_zoom' # AJAX-loaded canvas zoom
        post 'canvas', to: 'canvas#update' # Save updated canvas action
        get 'module_archive' # Module archive for single experiment
        get 'my_module_tags', to: 'my_module_tags#canvas_index'
        get 'archive' # archive experiment
        get 'clone_modal' # return modal with clone options
        post 'clone' # clone experiment
        get 'move_modal' # return modal with move options
        post 'move' # move experiment
        # get 'samples' # Samples for single project
        get 'updated_img' # Checks if the workflow image is updated
        get 'fetch_workflow_img' # Get udated workflow img
        # Renders sample datatable for single project (ajax action)
      #   post 'samples_index'
      #   post :delete_samples,
      #        constraints: CommitParamRouting.new(
      #          ExperimentsController::DELETE_SAMPLES
      #        ),
      #        action: :delete_samples
      end
    end

    # Show action is a popup (JSON) for individual module in full-zoom canvas,
    # as well as 'module info' page for single module (HTML)
    resources :my_modules, path: '/modules', only: [:show, :update] do
      resources :my_module_tags, path: '/tags', only: [:index, :create, :destroy] do
        collection do
          get :search_tags
        end
        member do
          post :destroy_by_tag_id
        end
      end
      resources :user_my_modules, path: '/users',
                only: [:index, :create, :destroy]
      resources :my_module_comments,
                path: '/comments',
                only: [:index, :create, :edit, :update, :destroy]
      # resources :sample_my_modules, path: '/samples_index', only: [:index]
      resources :result_texts, only: [:new, :create]
      resources :result_assets, only: [:new, :create]
      resources :result_tables, only: [:new, :create]
      member do
        # AJAX popup accessed from full-zoom canvas for single module,
        # as well as full activities view (HTML) for single module
        get 'description'
        get 'activities'
        post 'activities'
        get 'activities_tab' # Activities in tab view for single module
        get 'due_date'
        patch 'description',
              to: 'my_modules#update_description',
              as: 'update_description'

app/controllers/api/v1/reports_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ReportsController < BaseController
      before_action :load_team
      before_action :load_project
      before_action :load_report, only: :show

      def index
        reports = @project.reports
                          .page(params.dig(:page, :number))
                          .per(params.dig(:page, :size))
        render jsonapi: reports,
               each_serializer: ReportSerializer,
               hide_project: true
      end

      def show
        render jsonapi: @report,
               serializer: ReportSerializer,
               hide_project: true,
               include: :user
      end

      private

      def load_report
        @report = @project.reports.find(params.require(:id))
      end
    end
  end
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
  include StringUtility

  def render_new_element(hide)
    render partial: 'reports/elements/new_element.html.erb',
          locals: { hide: hide }
  end

  def render_report_element(element, provided_locals = nil)
    # Determine partial
    file_name = element.type_of
    if element.type_of.in? ReportExtends::MY_MODULE_CHILDREN_ELEMENTS
      file_name = "my_module_#{element.type_of.singularize}"
    end
    view = "reports/elements/#{file_name}_element.html.erb"

    # Set locals

    locals = provided_locals.nil? ? {} : provided_locals.clone

    children_html = ''.html_safe
    # First, recursively render element's children
    if element.comments? || element.project_header?
      # Render no children
    elsif element.result?
      # Special handling for result comments
      if element.has_children?
        children_html.safe_concat render_new_element(true)
        element.children.each do |child|
          children_html
            .safe_concat render_report_element(child, provided_locals)
        end
      else
        children_html.safe_concat render_new_element(false)
      end
    else
      if element.has_children?
        element.children.each do |child|
          children_html.safe_concat render_new_element(false)
          children_html
            .safe_concat render_report_element(child, provided_locals)
        end
      end
      children_html.safe_concat render_new_element(false)
    end
    locals[:children] = children_html

    if provided_locals[:export_all]
      # Set path and filename locals for files and tables in export all ZIP

      if element['type_of'] == 'my_module_repository'
        obj_id = element[:repository_id]
      elsif element['type_of'].in? %w(step_asset step_table result_asset
                                      result_table)

        parent_el = ReportElement.find(element['parent_id'])
        parent_type = parent_el[:type_of]
        parent = parent_type.singularize.classify.constantize
                            .find(parent_el["#{parent_type}_id"])

        if parent.class == Step
          obj_id = if element['type_of'] == 'step_asset'
                     element[:asset_id]
                   elsif element['type_of'] == 'step_table'
                     element[:table_id]
                   end
        elsif parent.class == MyModule
          result = Result.find(element[:result_id])
          obj_id = if element['type_of'] == 'result_asset'
                     result.asset.id
                   elsif element['type_of'] == 'result_table'
                     result.table.id
                   end
        end
      end

      if obj_id
        locals[:path] =
          provided_locals[:obj_filenames][element['type_of'].to_sym][obj_id]
          .sub(%r{/usr/src/app/tmp/temp-zip-\d+/}, '')
        locals[:filename] = locals[:path].split('/').last
      end
    end

    # ReportExtends is located in config/initializers/extends/report_extends.rb
    ReportElement.type_ofs.keys.each do |type|
      next unless element.public_send("#{type}?")

      element.element_references.each do |el_ref|
        locals[el_ref.class.name.underscore.to_sym] = el_ref
      end
      locals[:order] = element.sort_order if type.in? ReportExtends::SORTED_ELEMENTS
    end

    (render partial: view, locals: locals).html_safe
  end

  # "Hack" to omit file preview URL because of WKHTML issues
  def report_image_asset_url(asset)
    image_tag(asset.medium_preview
                   .processed
                   .service_url(expires_in: Constants::URL_LONG_EXPIRE_TIME))
  end

  # "Hack" to load Glyphicons css directly from the CDN
  # site so they work in report
  def bootstrap_cdn_link_tag
    specs = Gem.loaded_specs['bootstrap-sass']
    return '' unless specs.present?

    stylesheet_link_tag("http://netdna.bootstrapcdn.com/bootstrap/" \
                        "#{specs.version.version}/css/bootstrap.min.css",
                        media: 'all')
  end

  def font_awesome_cdn_link_tag
    stylesheet_link_tag(
      'https://maxcdn.bootstrapcdn.com/font-awesome' \
      '/4.6.3/css/font-awesome.min.css'
    )
  end

  def step_status_label(step)
    if step.completed
      style = 'success'
      text = t('protocols.steps.completed')
    else
      style = 'default'
      text = t('protocols.steps.uncompleted')
    end
    "<span class=\"label label-#{style}\">#{text}</span>".html_safe
  end

  # Fixes issues with avatar images in reports
  def fix_smart_annotation_image(html)
    html_doc = Nokogiri::HTML(html)
    html_doc.search('.atwho-user-popover').each do |el|
      text = el.content
      el.replace("<a href='#' style='margin-left: 5px'>#{text}</a>")
    end
    html_doc.search('[ref="missing-img"]').each do |el|
      tag = wicked_pdf_image_tag('icon_small/missing.png')
      el.replace(tag)
    end
    html_doc.to_s
  end

  private

  def obj_name_to_filename(obj, filename_suffix = '')
    obj_name = if obj.class == Asset
                 obj_name, extension = obj.file_name.split('.')
                 extension&.prepend('.')
                 obj_name
               elsif obj.class.in? [Table, Result, Repository]
                 extension = '.csv'
                 obj.name.present? ? obj.name : obj.class.name
               end
    obj_name = to_filesystem_name(obj_name)
    obj_name + "#{filename_suffix}#{extension}"
  end
end

app/views/reports/index.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<% provide(:head_title, t('projects.reports.index.head_title').html_safe) %>
<%= stylesheet_link_tag 'datatables' %>

<div class="content-pane">
  <div id="content-reports-index">
    <div class="row">
      <div class="col-md-12">
        <% if can_manage_reports?(current_team) %>
          <%= link_to '#', remote: true, class: 'btn btn-primary', id: 'new-report-btn' do %>
            <span class="fas fa-plus" aria-hidden="true"></span>
            <span class="hidden-xs"><%=t "projects.reports.index.new" %></span>
          <% end %>
          <%= link_to "", remote: true, class: "btn btn-secondary", id: "edit-report-btn" do %>
            <span class="fas fa-pencil-alt" aria-hidden="true"></span>
            <span class="hidden-xs"><%=t "projects.reports.index.edit" %></span>
          <% end %>
          <%= link_to "", remote: true, class: "btn btn-secondary", id: "delete-reports-btn" do %>
            <span class="fas fa-times" aria-hidden="true"></span>
            <span class="hidden-xs"><%=t "projects.reports.index.delete" %></span>
          <% end %>
        <% end %>
      </div>
    </div>
    <br />
    <div class="row">
      <div class="col-md-12">
        <div class="reports-datatable">
          <table id="reports-table"
                 class="table"
                 data-source="<%= reports_datatable_path(format: :json) %>">
            <thead>
              <tr>
                <th id="select-all"><input name="select_all" type="checkbox"></th>
                <th id="project-name"><%=t 'projects.reports.index.thead_project_name' %></th>
                <th id="report-name"><%=t 'projects.reports.index.thead_name' %></th>
                <th id="report-created-by"><%=t 'projects.reports.index.thead_created_by' %></th>
                <th id="report-last-modified-by"><%=t 'projects.reports.index.thead_last_modified_by' %></th>
                <th id="report-created-at"><%=t 'projects.reports.index.thead_created_at' %></th>
                <th id="report-updated-at"><%=t 'projects.reports.index.thead_updated_at' %></th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Save report modal -->
<div class="modal" id="delete-reports-modal" tabindex="-1" role="dialog" aria-labelledby="delete-reports-modal-label">
  <%= bootstrap_form_tag url: reports_destroy_path, method: :post, id: "delete-reports-form" do |f| %>
    <input type="hidden" name="report_ids" id="report-ids">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="delete-reports-modal-label"><%=t "projects.reports.index.modal_delete.head_title" %></h4>
        </div>
        <div class="modal-body">
          <%=t "projects.reports.index.modal_delete.message" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%=t "general.cancel" %></button>
          <%= f.button t("projects.reports.index.modal_delete.delete"), class: "btn btn-danger", id: "confirm-delete-reports-btn", name: nil %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<div class="modal" id="new-report-modal" tabindex="-1" role="dialog" aria-labelledby="create-reports-modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="new-report-modal-label"><%=t "projects.reports.index.modal_new.head_title" %></h4>
      </div>
      <div class="modal-body">
        <p><%=t "projects.reports.index.modal_new.message" %></p>
        <div class="form-group">
          <label><%=t "projects.reports.index.modal_new.projects" %></label>
          <% if @visible_projects&.length > 0 %>
            <select class="form-control selectpicker" data-abs-min-length="2" data-live-search="true">
              <% @visible_projects.each do |project| %>
                <option value="<%= project.path %>"><%= project.name %></option>
              <% end %>
            </select>
          <% else %>
            <p><%=t 'projects.reports.index.modal_new.no_projects' %></p>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%=t "general.cancel" %></button>
        <button id="new-report-reports-btn"
                class="btn btn-primary"
                data-new-report-path="<%= @visible_projects.first.path if @visible_projects.first %>"
                <%= 'disabled' unless @visible_projects&.length > 0 %>
                ><%=t 'projects.reports.index.modal_new.create' %></button>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag("reports/reports_datatable") %>

app/views/reports/new.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
  <meta name="turbolinks-visit-control" content="reload">
<% end %>

<% provide(:head_title, t("projects.reports.new.head_title", project: h(@project.name)).html_safe) %>

<%= render partial: "reports/new/report_navigation" %>

<div class="content-pane" id="report-new">
  <div class="report-container">
    <div
      id="data-holder"
      class="hidden"
      data-project-modal-title="<%=t "projects.reports.elements.modals.project_contents.head_title" %>"
      data-add-project-contents-url="<%= project_contents_modal_project_reports_url(@project) %>"
      data-add-experiment-contents-url="<%= experiment_contents_modal_project_reports_url(@project) %>"
      data-add-module-contents-url="<%= module_contents_modal_project_reports_url(@project) %>"
      data-add-step-contents-url="<%= step_contents_modal_project_reports_url(@project) %>"
      data-add-result-contents-url="<%= result_contents_modal_project_reports_url(@project) %>"
      data-stylesheet-url="<%= stylesheet_path "application" %>"
      data-print-title="<%=t "projects.reports.print_title", project: @project.name %>"
      data-project-id="<%= @project.id %>"
      data-save-report-url="<%= save_modal_project_reports_url(@project) %>"
      data-report-id="<%= @report.present? ? @report.id : "" %>"
      data-unsaved-work-text="<%=t "projects.reports.new.unsaved_work" %>"
      data-global-sort-text="<%=t "projects.reports.new.global_sort" %>"></div>

    <!-- Report "preview" -->
    <div id="report-content">

    <% if @report.present? %>
      <% @report.root_elements.each do |el| %>
        <%= render_report_element(el, local_assigns) %>
        <%= render_new_element(false) %>
      <% end %>
    <% else %>
      <%= render partial: "reports/elements/project_header_element", locals: { project: @project } %>
      <%= render partial: "reports/elements/new_element", locals: { initial: true } %>
    <% end %>
    </div>

    <!-- Add elements modal -->
    <div class="modal" id="add-contents-modal" tabindex="-1" role="dialog" aria-labelledby="add-contents-modal-label">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="add-contents-modal-label"></h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><%=t "general.cancel" %></button>
              <button type="button" data-action="add" class="btn btn-primary"><%=t "projects.reports.elements.modals.add" %></button>
            </div>
          </div>
        </div>
    </div>

    <!-- Save report modal -->
    <div class="modal" id="save-report-modal" tabindex="-1" role="dialog" aria-labelledby="save-report-modal-label">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="save-report-modal-label"><%=t "projects.reports.elements.modals.save_report.head_title" %></h4>
          </div>
          <div class="modal-body"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><%=t "general.cancel" %></button>
            <button type="button" data-action="save" class="btn btn-primary"><%=t "projects.reports.elements.modals.save_report.save" %></button>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<%= render partial: 'reports/new/save_PDF_to_inventory_modal' %>

<%= javascript_include_tag "handsontable.full.min" %>

<!-- Libraries for formulas -->
<%= render partial: "shared/formulas_libraries.html.erb" %>

<%= javascript_include_tag("reports/new") %>
<%= javascript_include_tag 'reports/save_pdf_to_inventory' %>

app/views/reports/report.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "application" %>
    <%= wicked_pdf_stylesheet_link_tag "reports_pdf" %>
    <%= bootstrap_cdn_link_tag %>
    <%= font_awesome_cdn_link_tag %>
  </head>
  <body class="print-report-body">
    <div class="print-report">
      <% # Also whitelist <img> and <input type="checkbox"> tags %>
      <%= sanitize_input(fix_smart_annotation_image(content),
                         %w(img input),
                         %w(type disabled checked)) %>
    </div>
  </body>
</html>